### ISSUE TITLE
Length of returned keys should be checked

### ISSUE THREAD

**Issue by inverted-capital** [kitsonk/kv-toolbox#12]
In the code that reassembles a blob, there is no check for an insidiously named child, which altho unlikely, could be guarded against with the simple addition of a key length check, as the list function grabs all child keys regardless of length:

https://github.com/kitsonk/kv-toolbox/blob/b18ec53b1a2bd06202be0d994c1c3213a78b7cff/blob.ts#L233-L257

A repro is here: https://dash.deno.com/playground/fair-owl-79

Yes, I should not be naming my keys using one of your reserved words, but no you shouldn't be taking words off me 😝 

So here, the reassembly function should only consider keys of keylength `key.length + 1` and ignore all others.

**Comment by kitsonk** [comment]
> Yes, I should not be naming my keys using one of your reserved words, but no you shouldn't be taking words off me 😝

It is a convention in JavaScript to name "private private" things with a `__`, combined with a leading and trailing `__` clearly means you mess with at your own peril. If you really want to use those words _caveat emptor_ is my feeling.

I might be inclined to skip any keys that are a) not a number and b) not the next in the sequence, but honestly, anyone who has gone to the trouble to figure out a very clearly private key that would never naturally occur and then add some subkeys to it... they clearly want to break stuff.  I am not sure what you are referring to about `keylength` as any number of the "parts" of a blob are not stored in the store (just the byte size in meta) and that is intentional.

**Comment by inverted-capital** [comment]
Ok understood.  I agree with your sentiment - this really is a minor point for completeness.

What I meant by key length, is that in the for loop, there should be an additional skip condition like so:

```js
for await (const item of list) { 
     if (item.key.length > key.length + 1) { 
         continue;
    }
    // rest of code remains the same
}
```

With this 3 line addition, the repro will no longer fail.

**Comment by kitsonk** [comment]
I hardened the whole which should make it pretty robust to people doing silly things.

**Comment by inverted-capital** [comment]
Thank you kindly 🙏 

People doing silly things might not be the library consumers - if I allow my users to pick their own filenames, someone could crash my app by naming their cat picture as `__kv_toolbox_blob__` and I, as a naïve library consumer, might not have thought to sanitize for that.

This caught me by surprise as I was doing directory listings in my app and got the whole recursive tree 🐳

**Comment by inverted-capital** [comment]
Hey I think there might be bug in your patch there ?

From the [KV docs](https://deno.land/api@v1.42.1?s=Deno.KvListOptions&unstable=#prop_reverse) the list iterator returns the keys in lexographical order, which means that 10 comes before 0, so for blobs of parts 10 or more, your function will break I think ?

**Comment by kitsonk** [comment]
The inline documentation is imprecise. This is how [key parts are really ordered](https://docs.deno.com/deploy/kv/manual/key_space#key-part-ordering).

There would have been big problems before that patch if they were order lexicographically by their string value. Plus there are tests where key parts are > 10 and validate that the pattern is reversible as well.

**Comment by inverted-capital** [comment]
Ah right! Excellent - thanks for that
